//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.12 at 01:43:44 AM CET 
//


package com.konzoomer.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import com.konzoomer.KapowDateAdapter;


/**
 * <p>Java class for StoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoreType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chainID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetBuildingIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postCodeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="districtName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="districtSubDivisionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactPerson" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="telefax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mondayOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="mondayClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="tuesdayOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="tuesdayClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="wednesdayOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="wednesdayClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="thursdayOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="thursdayClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="fridayOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="fridayClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="saturdayOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="saturdayClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="sundayOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="sundayClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="firstAndLastSundayInMonthOpen" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="firstAndLastSundayInMonthClose" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoreType", propOrder = {
    "chainID",
    "name",
    "streetName",
    "streetBuildingIdentifier",
    "postCodeIdentifier",
    "districtName",
    "districtSubDivisionIdentifier",
    "contactPerson",
    "telephone",
    "telefax",
    "email",
    "website",
    "latitude",
    "longitude",
    "mondayOpen",
    "mondayClose",
    "tuesdayOpen",
    "tuesdayClose",
    "wednesdayOpen",
    "wednesdayClose",
    "thursdayOpen",
    "thursdayClose",
    "fridayOpen",
    "fridayClose",
    "saturdayOpen",
    "saturdayClose",
    "sundayOpen",
    "sundayClose",
    "firstAndLastSundayInMonthOpen",
    "firstAndLastSundayInMonthClose"
})
public class StoreType {

    protected byte chainID;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String streetName;
    @XmlElement(required = true)
    protected String streetBuildingIdentifier;
    @XmlElement(required = true)
    protected String postCodeIdentifier;
    @XmlElement(required = true)
    protected String districtName;
    @XmlElement(required = true)
    protected String districtSubDivisionIdentifier;
    @XmlElement(required = true)
    protected String contactPerson;
    @XmlElement(required = true)
    protected String telephone;
    @XmlElement(required = true)
    protected String telefax;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String website;
    @XmlElement(defaultValue = "0")
    protected double latitude;
    @XmlElement(defaultValue = "0")
    protected double longitude;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mondayOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mondayClose;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tuesdayOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tuesdayClose;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar wednesdayOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar wednesdayClose;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar thursdayOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar thursdayClose;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fridayOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fridayClose;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar saturdayOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar saturdayClose;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar sundayOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar sundayClose;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstAndLastSundayInMonthOpen;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(KapowDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstAndLastSundayInMonthClose;

    /**
     * Gets the value of the chainID property.
     * 
     */
    public byte getChainID() {
        return chainID;
    }

    /**
     * Sets the value of the chainID property.
     * 
     */
    public void setChainID(byte value) {
        this.chainID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the streetBuildingIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetBuildingIdentifier() {
        return streetBuildingIdentifier;
    }

    /**
     * Sets the value of the streetBuildingIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetBuildingIdentifier(String value) {
        this.streetBuildingIdentifier = value;
    }

    /**
     * Gets the value of the postCodeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCodeIdentifier() {
        return postCodeIdentifier;
    }

    /**
     * Sets the value of the postCodeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCodeIdentifier(String value) {
        this.postCodeIdentifier = value;
    }

    /**
     * Gets the value of the districtName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * Sets the value of the districtName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictName(String value) {
        this.districtName = value;
    }

    /**
     * Gets the value of the districtSubDivisionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictSubDivisionIdentifier() {
        return districtSubDivisionIdentifier;
    }

    /**
     * Sets the value of the districtSubDivisionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictSubDivisionIdentifier(String value) {
        this.districtSubDivisionIdentifier = value;
    }

    /**
     * Gets the value of the contactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * Sets the value of the contactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPerson(String value) {
        this.contactPerson = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephone(String value) {
        this.telephone = value;
    }

    /**
     * Gets the value of the telefax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefax() {
        return telefax;
    }

    /**
     * Sets the value of the telefax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefax(String value) {
        this.telefax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the mondayOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getMondayOpen() {
        return mondayOpen;
    }

    /**
     * Sets the value of the mondayOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMondayOpen(XMLGregorianCalendar value) {
        this.mondayOpen = value;
    }

    /**
     * Gets the value of the mondayClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getMondayClose() {
        return mondayClose;
    }

    /**
     * Sets the value of the mondayClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMondayClose(XMLGregorianCalendar value) {
        this.mondayClose = value;
    }

    /**
     * Gets the value of the tuesdayOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getTuesdayOpen() {
        return tuesdayOpen;
    }

    /**
     * Sets the value of the tuesdayOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuesdayOpen(XMLGregorianCalendar value) {
        this.tuesdayOpen = value;
    }

    /**
     * Gets the value of the tuesdayClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getTuesdayClose() {
        return tuesdayClose;
    }

    /**
     * Sets the value of the tuesdayClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuesdayClose(XMLGregorianCalendar value) {
        this.tuesdayClose = value;
    }

    /**
     * Gets the value of the wednesdayOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getWednesdayOpen() {
        return wednesdayOpen;
    }

    /**
     * Sets the value of the wednesdayOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWednesdayOpen(XMLGregorianCalendar value) {
        this.wednesdayOpen = value;
    }

    /**
     * Gets the value of the wednesdayClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getWednesdayClose() {
        return wednesdayClose;
    }

    /**
     * Sets the value of the wednesdayClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWednesdayClose(XMLGregorianCalendar value) {
        this.wednesdayClose = value;
    }

    /**
     * Gets the value of the thursdayOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getThursdayOpen() {
        return thursdayOpen;
    }

    /**
     * Sets the value of the thursdayOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThursdayOpen(XMLGregorianCalendar value) {
        this.thursdayOpen = value;
    }

    /**
     * Gets the value of the thursdayClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getThursdayClose() {
        return thursdayClose;
    }

    /**
     * Sets the value of the thursdayClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThursdayClose(XMLGregorianCalendar value) {
        this.thursdayClose = value;
    }

    /**
     * Gets the value of the fridayOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getFridayOpen() {
        return fridayOpen;
    }

    /**
     * Sets the value of the fridayOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFridayOpen(XMLGregorianCalendar value) {
        this.fridayOpen = value;
    }

    /**
     * Gets the value of the fridayClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getFridayClose() {
        return fridayClose;
    }

    /**
     * Sets the value of the fridayClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFridayClose(XMLGregorianCalendar value) {
        this.fridayClose = value;
    }

    /**
     * Gets the value of the saturdayOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getSaturdayOpen() {
        return saturdayOpen;
    }

    /**
     * Sets the value of the saturdayOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaturdayOpen(XMLGregorianCalendar value) {
        this.saturdayOpen = value;
    }

    /**
     * Gets the value of the saturdayClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getSaturdayClose() {
        return saturdayClose;
    }

    /**
     * Sets the value of the saturdayClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaturdayClose(XMLGregorianCalendar value) {
        this.saturdayClose = value;
    }

    /**
     * Gets the value of the sundayOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getSundayOpen() {
        return sundayOpen;
    }

    /**
     * Sets the value of the sundayOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSundayOpen(XMLGregorianCalendar value) {
        this.sundayOpen = value;
    }

    /**
     * Gets the value of the sundayClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getSundayClose() {
        return sundayClose;
    }

    /**
     * Sets the value of the sundayClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSundayClose(XMLGregorianCalendar value) {
        this.sundayClose = value;
    }

    /**
     * Gets the value of the firstAndLastSundayInMonthOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getFirstAndLastSundayInMonthOpen() {
        return firstAndLastSundayInMonthOpen;
    }

    /**
     * Sets the value of the firstAndLastSundayInMonthOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstAndLastSundayInMonthOpen(XMLGregorianCalendar value) {
        this.firstAndLastSundayInMonthOpen = value;
    }

    /**
     * Gets the value of the firstAndLastSundayInMonthClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public XMLGregorianCalendar getFirstAndLastSundayInMonthClose() {
        return firstAndLastSundayInMonthClose;
    }

    /**
     * Sets the value of the firstAndLastSundayInMonthClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstAndLastSundayInMonthClose(XMLGregorianCalendar value) {
        this.firstAndLastSundayInMonthClose = value;
    }

}
